# Generated by Django 5.0.3 on 2024-03-14 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0006_remove_fornecedor_produtos_fornecedor_produtos'),
        ('produtos', '0002_remove_produto_fornecedor_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor'),
        ),
    ]
