# Generated by Django 5.0.3 on 2024-03-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_fornecedor_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria_FK',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoria'),
        ),
    ]
