# Generated by Django 5.0.3 on 2024-03-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produto_categoria_fk_produto_categoria_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_validade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
