# Generated by Django 5.0.3 on 2024-03-14 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_alter_fornecedor_estado'),
        ('produtos', '0002_remove_produto_fornecedor_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='produtos',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='produtos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto'),
        ),
    ]
