# Generated by Django 5.0.3 on 2024-03-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0005_remove_fornecedor_produtos_fornecedor_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='produtos',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='produtos',
            field=models.CharField(default='', max_length=255),
        ),
    ]
