# Generated by Django 5.0.3 on 2024-03-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0007_remove_fornecedor_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(max_length=15),
        ),
    ]
